name: texa_core
description: "Nexa ecosystem mobile application."
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ^3.10.4

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2
  get_it: ^9.2.0
  injectable: ^2.7.1
  freezed_annotation: ^3.1.0
  go_router: ^17.0.1
  dio: ^5.9.0
  retrofit: ^4.9.2
  flutter_bloc: ^9.1.1
  cupertino_icons: ^1.0.8
  lucide_icons: ^0.257.0
  shared_preferences: ^2.5.4
  json_annotation: ^4.9.0
  equatable: ^2.0.8
  flutter_svg: ^2.2.3
  flutter_secure_storage: ^10.0.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: ^2.10.4
  injectable_generator: ^2.12.0
  retrofit_generator: ^10.2.1
  freezed: ^3.2.4
  json_serializable: ^6.11.3


flutter:
  uses-material-design: true
  generate: true
